In [64]:
import numpy as np

### Aim: generate strings of L bits;
### in each string, one out of M patterns is enforced

In [116]:
# random seed for reproducibility
np.random.seed(12345)

def pattern(X,l0,l1):
    """ zeros in the positions of list l0,
        ones in the positions of list l1"""
    X[l0] = 0
    X[l1] = 1
    return X
xx = np.random.randint(0,2,size=L)
print(xx)
xx = pattern(xx,[0,1,2,3,4,5,6,7],[-8,-7,-6,-5,-4,-3,-2,-1])
print(xx)

[0 1 1 1 0 1 0 0 1 0 1 1 0 1 1 0 1 1 1 0 0 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1]
[0 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1 1 1 1 1 1 1 1]


In [119]:
# random seed for reproducibility
np.random.seed(12345)
N=400
L=36
M=5
y = np.zeros(N).astype(int)
x = np.random.randint(0,2,size=(N,L))

for n in range(4):
    print(x[n])
print("")

for n in range(N):
    y[n] = np.random.randint(0,M) # numpy: 0 to M-1, if M
        
    if y[n]==0:
        x[n] = pattern(x[n],[3,4,14,16,22,25,27,32],[0,5,7,9,12,15,26,30])
    elif y[n]==1:
        x[n] = pattern(x[n],[0,11,12,23,24,28,33],[2,4,6,25,26,30,31])
    elif y[n]==2:
        x[n] = pattern(x[n],[0,5,8,15,19,34],[5,9,10,15,26,29])
    elif y[n]==3:
        x[n] = pattern(x[n],[6,7,16,24,26],[3,5,13,16,27])
    elif y[n]==4:
        x[n] = pattern(x[n],[5,12,22,28],[4,5,30,34])
            
for n in range(30):
    print(x[n],y[n])

[0 1 1 1 0 1 0 0 1 0 1 1 0 1 1 0 1 1 1 0 0 0 1 1 1 0 1 0 0 1 1 1 1 1 0 1]
[1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 0 1 1 1 0 0 1 0 1 0]
[0 0 1 1 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 1 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 0]
[0 1 1 0 0 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 0 0 0 1 0 1 0 0 1 1 0 1]

[0 1 1 1 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1 0 0 0 1 0 0 1 1 0 0 1 1 1 1 0 0 1] 1
[1 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 1 1 1 0 1 1 0 0 0 0 1 1 1 0 0 1 0 1 0] 3
[0 0 1 1 0 1 0 0 0 1 1 0 0 0 1 1 0 1 1 0 1 1 1 0 0 0 1 0 0 1 0 1 0 1 0 0] 2
[0 1 1 1 0 1 0 0 0 0 1 1 0 1 1 0 1 1 0 0 1 1 1 1 0 0 0 1 0 1 0 0 1 1 0 1] 3
[0 1 0 1 1 1 0 1 0 1 1 1 1 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 1 0 0 1] 2
[0 1 1 0 1 1 0 0 1 1 1 1 0 1 1 0 1 1 1 0 0 0 0 0 1 1 1 0 0 1 1 1 0 1 1 0] 4
[0 0 1 1 0 1 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 0 0 1 0] 3
[0 0 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1 0 1 1 1 0 1 0 0 1 1 0 0 0 1 1 0 0 1 0] 1
[0 0 1 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0] 4
[1 1 1 0 0 1 0 1 1 

In [110]:
# create directory DATA
!mkdir DATA

str0 = f'M{M}_N{N}'
print(str0)
fname='DATA/x_'+str0+'.csv'
np.savetxt(fname,x,delimiter=" ",fmt='%i')
fname='DATA/y_'+str0+'.csv'
np.savetxt(fname,y,fmt='%i')

mkdir: cannot create directory ‘DATA’: File exists
M5_N400
